import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ 
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Belajar Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  let header = (
    <header className = "navbar">
        <div className="flex justify-between">
          <Link className = 'judul' href = '/'>CRONIT SHOP</Link>
          <div className = "menu">
            <Link href = '/api/products'>Products</Link>
            <Link href= '/profile'>Profile</Link>
            <Link href = '/contact'>Contact</Link></div></div>
    </header>
  )
  let footer = (
    <footer>
      <p>100% Handmade</p>
    </footer>
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {header}
          <div className='mt-8'>{children}</div>
          {footer}
        </div>
      </body>
    </html>
  );
}
