import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { mkdir } from "fs";
import Link from "next/link";
import { INTERNALS } from "next/dist/server/web/spec-extension/request";

const inter = Inter({ 
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Belajar Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let header = (
    <header className = "navbar">
        <div className = "navbar-start px-3">
            <Link href = '/'><h1>CRONIT SHOP</h1></Link></div>
        <div className = "navbar-end">
            <div>
                <Link href = '/products'>Products</Link></div>
            <div>
                <Link href= '/profile'>Profile</Link></div>
            <div>
                <Link href = '/contact'>Contact</Link></div>
        </div>
    </header>
  )
  let footer = (
    <footer>
      <p>100% Handmade</p>
    </footer>
  )
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
